i18n(de): Add German translation
pop-os/cosmic-term pull request #185
Opened 2024-04-15 22:22 UTC by GrumiumXD

2024-04-16 08:18 UTC, leb-kuchen commented on i18n/de/cosmic_term.ftl
> +match-desktop = An system anpassen
This is a noun

2024-04-16 08:51 UTC, leb-kuchen requested changes

2024-04-16 08:51 UTC, leb-kuchen commented on i18n/de/cosmic_term.ftl
> +profile = Profile
`Profil`, this is a singular

2024-04-16 08:51 UTC, leb-kuchen commented on i18n/de/cosmic_term.ftl
> +tab-title-description = Standard Titel des Tabs überschreiben
This should be one word. ´Standardtitel´

2024-04-16 08:51 UTC, leb-kuchen commented on i18n/de/cosmic_term.ftl
> +zoom-reset = Standard Schriftgröße
This should also be one world: `Standardschriftgröße`

2024-04-16 09:43 UTC, GrumiumXD commented
Yeah, shouldn't do things that rely on correct spelling in the middle of the night...

Thanks for checking. I corrected the areas you pointed out.

2024-04-16 13:12 UTC, leb-kuchen commented
Looks fine

2024-04-16 13:25 UTC, leb-kuchen approved these changes

2024-04-26 01:59 UTC, jackpot51 approved these changes

2024-04-26 01:59 UTC, merged